# Generated by Django 2.2 on 2019-05-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_author', models.CharField(max_length=200)),
                ('item_reader', models.CharField(max_length=200)),
                ('item_date', models.IntegerField(default=0)),
                ('item_description', models.TextField(max_length=2000)),
                ('votes', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share.Catalogue')),
            ],
        ),
    ]
