# Generated by Django 2.2 on 2019-05-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_author',
            new_name='item_url',
        ),
        migrations.RemoveField(
            model_name='item',
            name='votes',
        ),
        migrations.AddField(
            model_name='item',
            name='item_conf',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
